### ISSUE TITLE
PyPI installs "successfully" for Python 3.x, but won't import

### ISSUE THREAD

**Issue by hosford42** [dcramer/py-wikimarkup#6]
The installer *appears* to work:

    C:\>pip install py-wikimarkup
    Collecting py-wikimarkup
      Downloading py-wikimarkup-1.0.2.tar.gz
    Installing collected packages: py-wikimarkup
      Running setup.py install for py-wikimarkup
    Successfully installed py-wikimarkup-1.0.2

But the module can't be imported:

    >>> import wikimarkup
    Traceback (most recent call last):
      File "<string>", line 301, in runcode
      File "<interactive input>", line 1, in <module>
      File "C:\Installs\Python33\lib\site-packages\wikimarkup\__init__.py", line 1, in <module>
        from parser import parse, parselite, registerTagHook
    ImportError: cannot import name parse

And neither can the sub-modules:

    >>> from wikimarkup import parse
    Traceback (most recent call last):
      File "<string>", line 301, in runcode
      File "<interactive input>", line 1, in <module>
      File "C:\Installs\Python33\lib\site-packages\wikimarkup\__init__.py", line 1, in <module>
        from parser import parse, parselite, registerTagHook
    ImportError: cannot import name parse

A tag can be added to the PyPI distribution to flag it as `Python 2.x Only` if Python 3.x is not going to be supported. It probably ought to be mentioned in the docs, too.

**Comment by jcopps** [comment]
I am not sure why. 
I also had this package installed: https://pypi.org/project/wikimarkup/.
Upon uninstalling this, I got rid of this parse import error.

**Comment by jcopps** [comment]
Looks like the strings in parser.py needs 3.x compatible prefixes.
